on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    uses: r-lib/actions/.github/workflows/check-standard.yaml@v2
    with:
      working-directory: .
